server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp:localhost:9080/~/puppyPopularVote
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework: INFO
    org.springframework.web: INFO
